version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: fly_me
    container_name: fly_me_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini:ro # opcional
    networks:
      - app-network

  web:
    image: nginx:1.25
    container_name: fly_me_web
    restart: unless-stopped
    ports:
      - "8080:80"   # acesse http://localhost:8080
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: fly_me_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpass
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306" # opcional, para acesso externo
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
